version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            bundle install --jobs=3 --retry=3 --path=$PWD/vendor/bundle
      - run:
          name: test
          command: |
            bundle exec rake spec

workflows:
  version: 2
  test:
    jobs:
      - build